### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by llaville** [box-project/box#1259]
Hello 

Is there a good reason why you dropped support of PHP 8.1 since BOX 4.6.0 ?

https://www.php.net/supported-versions.php

Thanks in advance for your answer

**Comment by theofidry** [comment]
A reason yes, whether it's good or not is debatable I suppose 😅 

- PHP 8.1 is security fix only
- Upgrading from PHP 8.1 to 8.2 is relatively easy
- Adding another PHP version adds a lot of tests to the matrix (around +50 IIRC)
- Box is a build tool, so that it requires 8.2 does not mean that the code compiled is limited 8.2, it can build projects that target 7.2 without issues

**Comment by theofidry** [comment]
I hope that answers the question and that it's not too big of a problem for you

**Comment by llaville** [comment]
@theofidry You've probably forgot another context, that still require a specific version such as PHP 8.1, because we want to distribute a based PHP 8.1 version of a project compiled.
See https://github.com/overtrue/phplint/blob/9.1/.github/workflows/release.yml

I used  PHP 8.1, and of course Box 4.5 to build the PHAR version of PHPLint that will be attached to the release notes

**Comment by theofidry** [comment]
>because we want to distribute a based PHP 8.1 version of a project compiled.

This is what `platform.php` is for in `composer.json` though? For example I build the requirement checker, which is a PHP 7.2 application, with PHP 8.2.

**Comment by llaville** [comment]
Ok. Forgot this alternative. Thanks to remember me !
