### ISSUE TITLE
box.phar missing from 3.12.0 release

### ISSUE THREAD

**Issue by GrahamCampbell** [box-project/box#530]

**Comment by danepowell** [comment]
@theofidry can you take a look please? This is actually quite serious, as many projects probably download Box in their CI scripts like `curl -L https://github.com/humbug/box/releases/latest/download/box.phar`. This causes hard-to-debug failures because box.phar still downloads but it's just a 404 file.

**Comment by szepeviktor** [comment]
> many projects probably download Box in their CI scripts like

_Dear CI scripts!_

Please use wget as its return status is 8 when HTTP/404 is received.

**Comment by szepeviktor** [comment]
@smoench Could you upload a single PHAR file for us?
https://github.com/box-project/box/releases/tag/3.12.0

**Comment by smoench** [comment]
No, I'm sorry. I don't have rights for that. The reason why nothing were uploaded was a failing pipeline https://github.com/box-project/box/actions/runs/629384649. I tried to propose a quickfix with https://github.com/box-project/box/pull/535 using ubuntu-18.04 because there were some strange failures and latest successful run was with ubuntu-18.04. But there are still some errors. So I think the cause is related to https://github.com/box-project/box/pull/529. I guess it has updated more than expected.

I'm sure if one can propose a fix, Théo will merge and tag a new release.

**Comment by smoench** [comment]
Finally I could fix the pipeline in #535.

@theofidry before releasing a new release for box, a new release for php-scoper is needed with the following fix https://github.com/humbug/php-scoper/pull/466 which should be included in the new box release as well.

**Comment by theofidry** [comment]
@smoench thanks for the note, will do a release in the coming week

**Comment by smoench** [comment]
Would it be possible having a bugfix release as soon as possible? Because nearly all tools relying on latest Symfony and using scoping are failing to build. The symfony string component uses `parent` [return types](https://github.com/symfony/string/blob/5.x/UnicodeString.php#L203) which is in the [requirements](https://github.com/symfony/console/blob/5.x/composer.json#L25) of symfony console.

Let me know how I can help you :-)

**Comment by theofidry** [comment]
Once I'm off work and it's not 1am :)

**Comment by szepeviktor** [comment]
@theofidry Thank you.
So we won't have PHAR files in release attachments?

**Comment by smoench** [comment]
@szepeviktor the latest tag has a phar file attached https://github.com/box-project/box/releases/tag/3.12.2

**Comment by theofidry** [comment]
>So we won't have PHAR files in these release attachments?

You do when the CI works, but if it failed it's very unlikely that I'll manually build and upload it

**Comment by szepeviktor** [comment]
Thank you very much for clarifying that.
