### ISSUE TITLE
Dump file list without outputting .phar

### ISSUE THREAD

**Issue by robocoder** [box-project/box#532]
## Feature Request

Provide a compile option (e.g., --dry-run) that dumps the list of files that would have been included in the phar without generating the .phar file.

Rationale:
* in box.json, `output` cannot be set to, for example, "/dev/null"
* less space utilization (compared to generating .phar or using --debug)

**Comment by theofidry** [comment]
I do think it's a good idea however:

- It would require more than "not building the PHAR" but as well providing a comprehensive list of the files (and whether they will be scoped or not). Also would require to mention if something would change due to the autoloader being dumped or something
- Would require to disable quite a few checks (no restart/parallel, memory bump, file descriptor limit bump, etc.)

So if implemented it would likely be a completely different command. Whilst I do like the benefit of it, I think the feature requires too many changes for it to be worthwhile at least in the current state.
