### ISSUE TITLE
Phar does not work as expected without the .phar extension

### ISSUE THREAD

**Issue by kbond** [box-project/box#558]
I'm having an issue with [this project](https://github.com/kbond/phpmyadmin-server) when running as a phar without the `phar` extension.

When running the phar with the extension `php phpmyadmin.phar` or if executable, just `phpmyadmin.phar` it works exactly as expected.

When I rename the file to remove the `phar` extension (so it becomes `phpmyadmin`), I get the following error:

```
[Mon Jul 26 10:46:28 2021] PHP 7.4.18 Development Server (http://127.0.0.1:8888) started
[Mon Jul 26 10:46:29 2021] 127.0.0.1:51264 Accepted
[Mon Jul 26 10:46:29 2021] PHP Warning:  Unknown: failed to open stream: phar error: invalid url or non-existent phar &quot;phar:///path/to/phpmyadmin/vendor/symfony/web-server-bundle/Resources/router.php&quot; in Unknown on line 0
[Mon Jul 26 10:46:29 2021] PHP Fatal error:  Unknown: Failed opening required 'phar:///path/to/phpmyadmin/vendor/symfony/web-server-bundle/Resources/router.php' (include_path='.:/usr/share/php') in Unknown on line 0
[Mon Jul 26 10:46:29 2021] 127.0.0.1:51264 Closing
```

This occurs when running with php (`php phpmyadmin`) or an executable (`./phpmyadmin`).

I could use some help figuring this out - did I miss a config option?

_Apologies for not using the slack channel but I couldn't find it._

**Comment by kbond** [comment]
I _think_ you can't include a file from a phar w/o the phar extension. [Related Stack Overflow question](https://stackoverflow.com/questions/59302726/include-php-phar-without-phar-extension).

 If what I'm experiencing is simply a _PHP limitation_, this issue can be closed. I did create a workaround in my project.

**Comment by theofidry** [comment]
I can confirm it's a PHP limitation :/

I believe the reason is that when you have `'phar:///path/to/phpmyadmin/vendor/symfony/web-server-bundle/Resources/router.php'`, without the `.phar` then PHP can't know which part of the path is the root and so is unable to deduce the path of the file within the PHAR. I do not know if this could be solved within PHP itself, but I highly doubt anyone is gonna bother tbh as PHARs are not actively worked on AFAICT
