### ISSUE TITLE
Reusable `requirement-checker` -- explains two distinct directories

### ISSUE THREAD

**Issue by llaville** [box-project/box#647]
Could you explains the difference between `.requirement-checker` and `requirement-checker` directories we can found in `master` branch and even on latest release `3.16` ?

- Usage ? 
- Behaviour ? 
- Feature ?

**Comment by llaville** [comment]
I've found an issue when I reused `box` with `.requirement-checker` folder identified by https://github.com/box-project/box/blob/3.16.0/src/RequirementChecker/RequirementsDumper.php#L35 inside a PHAR.

**Comment by llaville** [comment]
> I've found an issue when I reused `box` with `.requirement-checker` folder identified by https://github.com/box-project/box/blob/3.16.0/src/RequirementChecker/RequirementsDumper.php#L35 inside a PHAR.

After encountered an issue with `check-requirements` setting of BOX on my project `bartlett/box-manifest` v1.0.1,  I've finally found origin of issue and will release a new bugfix 1.0.2 in few minutes.

At least, with official BOX project we have 2 autoloaders that we have to register, in case of reusable BOX source code inside a PHAR container.
And even one more if we consider that we should be able to load user project source code.

Anyway, the question is still available. Contributors should know the differences ... Thanks in advance for your answer !

**Comment by llaville** [comment]
FYI: Bad news. The issue I've found is not related to autoloader but to https://github.com/box-project/box/issues/649

**Comment by llaville** [comment]
Workaround exists. In my context, I must force to add the directory beginning with dot (`.requirement-checker`)

```
    "directories": ["bin", "src", "vendor"],
    "directories-bin": ["vendor/humbug/box/.requirement-checker"],
```

**Comment by theofidry** [comment]
`requirement-checker` is the source code of the requirement checker component. The strategy adopted to deliver the [requirement checker feature](https://github.com/box-project/box/blob/master/doc/requirement-checker.md#requirements-checker) to the built PHARs, Box needs to bundle this requirement-checker code into the built PHAR, this means two things:

- Box itself needs to know the requirement-checker code in order to ship it in the PHAR it will build
- The requirement checker code will be added to the built PHARs

In order to reduce the clutter, and ship a more "optimized" version, I compile the `requirement-checker` code and dump it into `.requirement-checker`: this is what will be shipped in Box.

In order to avoid namespaces colliding, I scope the requirement checker (the `.requirement-checker` is scoped). Ideally, this would be unique, i.e. if I build two PHARs `foo.phar` and `bar.phar`, they should (ideally) have different requirement checker codes, i.e. the requirement checker code shipped into a PHAR is unique. However, in practice it was too much efforts. Since the requirement-checker code is small, simple and only shipped into PHARs (it's not a published packagist code), I believe that having a unique version per Box version is good enough.

**Comment by theofidry** [comment]
Since the question has been answered I'll be closing this :)

If you need more information I'll happily re-open it or reply in a new issue.
