### ISSUE TITLE
Add a warning message if custom stub is not PHP syntax valid

### ISSUE THREAD

**Issue by llaville** [box-project/box#950]
## Feature Request

When we declare a custom stub in the BOX configuration file, it will be helpful to know if it is not PHP syntax valid (a check with PHP linter is enough).

Add a new warning message if there are some syntax errors !

**Comment by theofidry** [comment]
It sounds like a good idea, but I'm not sure if the benefit is there.

I really like the idea, but after some consideration I think it's a false good idea.

I see two big problems with it:

- It will not really catch any mistake: when you create a PHAR, it's a process on its own. You _need_ to test it somehow, even if it's a simple smoke test such as `foo.phar --version`. In which case any of those tests will pick up an invalid stub, be it because the stub is an invalid PHP file or it's a valid PHP file but not doing what you expect.
- The PHP binary used for _compiling_ your PHAR is not necessarily the one used for _executing_ the PHAR. For example, you could compile your PHAR in PHP 8.1 but your PHAR require PHP 8.2+.

So I think trying to implement this is far from being trivial and in the end will not really achieve what you want.
